# Generated by Django 3.2.12 on 2022-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220411_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
