# Generated by Django 3.2.12 on 2022-06-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exclusions',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
