# Generated by Django 3.2.12 on 2022-04-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20, null=True)),
                ('stage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('batch_id', models.CharField(max_length=20, null=True)),
                ('stage', models.IntegerField(default=0)),
                ('finished_page', models.IntegerField(default=0)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leadlist')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('data_id', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=400, null=True)),
                ('domain', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('snippet', models.CharField(max_length=400, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('linkedin_title', models.CharField(max_length=100, null=True)),
                ('linkedin_url', models.CharField(max_length=200, null=True)),
                ('employee_count', models.IntegerField(null=True)),
                ('employee_order', models.CharField(max_length=2000, null=True)),
                ('contact_name', models.CharField(max_length=50, null=True)),
                ('contact_title', models.CharField(max_length=50, null=True)),
                ('contact_linkedin', models.CharField(max_length=200, null=True)),
                ('contact_verified_email', models.CharField(max_length=30, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.search')),
            ],
        ),
    ]
