# Generated by Django 3.2.12 on 2022-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leadlist_target_num_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='job_titles',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
