# Generated by Django 3.2.12 on 2022-04-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leadlist_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='reached_end',
            field=models.BooleanField(default=False),
        ),
    ]
