# Generated by Django 3.2.12 on 2022-05-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leadlist_unique_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='contact_verified_email',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='domain',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
