# Generated by Django 3.2.12 on 2022-05-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220505_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
