# Generated by Django 3.2.12 on 2022-05-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_searchresult_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='contact_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='contact_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
