# Generated by Django 3.2.12 on 2022-05-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220517_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='contact_verified_email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
