# Generated by Django 3.2.12 on 2022-05-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_searchresult_contact_verified_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
